server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000
      connection-test-query: SELECT 1
      connection-timeout: 10000
      minimum-idle: 2
  jpa:
    show-sql: true


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml

#showSql
logging:
  level:
    com:
      xjx:
        mapper : debug